# Generated by Django 6.0.6 on 2026-07-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.CharField(max_length=1000, verbose_name='источник (ссылка/файл)')),
                ('source_type', models.CharField(default='youtube', max_length=16)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('title_ar', models.CharField(blank=True, max_length=300)),
                ('reciter', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('queued', 'в очереди'), ('processing', 'обрабатывается'), ('ready', 'готово'), ('error', 'ошибка')], default='queued', max_length=16)),
                ('stage', models.CharField(blank=True, max_length=64)),
                ('error', models.TextField(blank=True)),
                ('audio_filename', models.CharField(blank=True, max_length=300)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
