# Generated by Django 6.0.6 on 2026-07-03 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recitation',
            name='gstt_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='AsrRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognizer', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('queued', 'в очереди'), ('processing', 'обрабатывается'), ('ready', 'готово'), ('error', 'ошибка')], default='queued', max_length=16)),
                ('stage', models.CharField(blank=True, max_length=64)),
                ('error', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='recitations.recitation')),
            ],
            options={
                'ordering': ('recognizer',),
                'constraints': [models.UniqueConstraint(fields=('recitation', 'recognizer'), name='uniq_recitation_recognizer')],
            },
        ),
    ]
