# Generated by Django 6.0.6 on 2026-07-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recitations', '0003_migrate_legacy_data_to_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='recitation',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
